### ISSUE TITLE
libgfortran.so.4 missing

### ISSUE THREAD

**Issue by probonopd** [Lateralus138/UniShellect#1]
```
me@host:~$ Downloads/unishellect-x86_64.AppImage 
/tmp/.mount_unisheiXDpR7/usr/bin/unishellect: error while loading shared libraries: libgfortran.so.4: cannot open shared object file: No such file or directory
```

Please bundle it inside the AppImage. All libraries except those on https://github.com/AppImage/pkg2appimage/blob/master/excludelist should be bundled.

Tools like https://github.com/probonopd/go-appimage/tree/master/src/appimagetool can do it for you.

Reference:
https://github.com/AppImage/appimage.github.io/pull/2229

**Comment by Lateralus138** [comment]
I'm looking into this, but my program is not dependent on any library at all.
I imagine I should just add that .so to the exclude list?

**Comment by probonopd** [comment]
Well, as the error message shows, the `unishellect` binary inside the AppImage cannot run without `libgfortran.so.4`. So it should be bundled inside the AppImage.

**Comment by Lateralus138** [comment]
How do I find out the correct lib version? I imagine it the so should run with 16.04, but I'm on an 20.04 machine.

**Comment by probonopd** [comment]
As a general rule of thumb, you should build the AppImage on a Linux distribution no newer than the oldest still-supported LTS release. Which in practical terms currently means Ubuntu xenial.

**Comment by Lateralus138** [comment]
I just provided the lib and compiled and tested on 20.04 and compiled 16.04 run here:
[Xenial Build Run](https://github.com/Lateralus138/UniShellect/runs/986370534)
Seems sucessful.

**Comment by probonopd** [comment]
Can it be downloaded somewhere?

By the way, to check what libraries a binary needs:

```
me@host:~$ ldd Downloads/unishellect
	linux-vdso.so.1 (0x00007fffeedaf000)
	libgfortran.so.4 => not found
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa620ddc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa6209eb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa621207000)
```

See that `libgfortran.so.4 => not found`?

**Comment by Lateralus138** [comment]
I've moved the lib into lib folders it's showing there in your message; which is different (of course) from what I was thinking and where I had it.
I've compiled again; maybe it works. The only test env I can use is at GitHub Actions; I can't figure TravisCI out for the life of me (though I haven't invested a lot of time).

**Comment by Lateralus138** [comment]
I'll try compiling in Ubuntu 16.04 in VirtualBox today.

**Comment by Lateralus138** [comment]
So I'm pretty sure I've sussed out the issue and I'm not sure it can be solved.

It seems it seems Fortran applications compiled with gfortran in in Xenial uses the '3' version of the library and the gfortran version on Ubuntu 20.04 compiles with '4', but Fortran applications compiled with '4' won't run on machines with 3 and  vice version. What I can probably do is compile both versions and make AppImages for both versions, but the AppImage for the '4' version won't pass your test.

**Comment by probonopd** [comment]
What you need to do is compile on xenial and bundle the 3 version of the library in the AppImage, e.g., using tools like `linuxdeployqt` or https://github.com/probonopd/go-appimage/tree/master/src/appimagetool.

Then it should run on all still-supported distributions, no matter whether Fortran is installed or not, and no matter in which version.

**Comment by Lateralus138** [comment]
Okay, had to take a break, but I have figured out what I was doing wrong. I was not setting my paths correctly in AppRun.

I have successfully tested this new AppImage in `Ubuntu 16.04 Xenial` and `Linux Lite` and in both environments no Fortran environment was installed with no sign of gcc/gfortran or 'libgfortran.so.4'  except for the one inside the .AppImage.

I also included any other libs found with:
```Bash
 $ ldd unishellect
```
so there should be good no matter what.

The latest AppImage build should be here:
[https://github.com/Lateralus138/UniShellect/releases/tag/Continuous](https://github.com/Lateralus138/UniShellect/releases/tag/Continuous)
and here:
[https://github.com/Lateralus138/UniShellect/blob/master/dist/appimage/unishellect-x86_64.AppImage](https://github.com/Lateralus138/UniShellect/blob/master/dist/appimage/unishellect-x86_64.AppImage)

**Comment by probonopd** [comment]
Thank you very much :+1:
